### ISSUE TITLE
Pointer Lock Interface names must be prefixed

### ISSUE THREAD

**Issue by jsiwkowski** [colevk/dark-souls-map-viewer#1]
Pointer Lock Interface names in Firefox & webkit-based browsers are prefixed with 'moz' and 'webkit' respectively. Base names are not recognized unless set up like this

``` javascript
Element.prototype.requestPointerLock =
    Element.prototype.requestPointerLock
    || Element.prototype.mozRequestPointerLock
    || Element.prototype.webkitRequestPointerLock;
```

PS great job you did with this project :)

**Comment by colevk** [comment]
Hey, thanks for the interest! Chrome uses the `requestPointerLock` element and not any of the others, and since this is a Chrome app anyways I took out the others.

At least that's what I was assuming, since it works on my computer. Does this break on your browser version/OS?

**Comment by jsiwkowski** [comment]
Yup, Win7 + FF42. It appears that it's quite enough to use this method with `||` selecting. `addEventListener()` needs to be called for a proper event name, so that should do

``` javascript
for (_p in ["", "moz", "webkit"]) {
    var _e = "on" + _p + "pointerlockchange";
    if (_e in document) document.addEventListener(_e, ...);
}
```

I was thinking of forking and writing something myself, but couldn't gather my thoughts.

**Comment by colevk** [comment]
I've put back all the stuff I took out when I made this a Chrome app. Let me know if this fixes things for you, because I can't test anything on Windows.

**Comment by jsiwkowski** [comment]
Yes, now it works like a charm :) Many thanks :)
Dnia 18 listopada 2015 22:23 Cole van Krieken &lt;notifications@github.com&gt; napisał(a):
I've put back all the stuff I took out when I made this a Chrome app. Let me know if this fixes things for you, because I can't test anything on Windows.—
